Match env var with requirement
SoftingAE-VCPI/VCPI.android.platform.system.core pull request #4
Opened 2024-01-25 08:40 UTC by ahsan-l4b

Set EXTERNAL_STORAGE to /mnt/softing/softing_sdd_0

L4B Ticket: vcpi-449
Change-Id: I757657a6af7c1fa160dc5a146ea96330fa7b8f24

2024-01-25 12:30 UTC, inf265 approved these changes

2024-03-06 10:50 UTC, softing-amr requested changes
The SSD is currently mounted to
/mnt/softing/softing_ssd
and this location shall not be changed.

Where does the requirement come from that we need the environment variable EXTERNAL_STORAGE?
What is it used for?

@silvio @inf265 Do you know this?

2024-03-06 12:03 UTC, Emanuel-l4b approved these changes

2024-03-06 12:25 UTC, ahsan-l4b commented
> The SSD is currently mounted to /mnt/softing/softing_ssd and this location shall not be changed.
> 
> Where does the requirement come from that we need the environment variable EXTERNAL_STORAGE? What is it used for?
> 
> @silvio @inf265 Do you know this?

@softing-amr - When an external storage either SSD or SDCard is present; it always mounted at  /mnt/softing/softing_ssd_X (This is by requirement and is managed by Parameter Server).
 
Currently, the env variable EXTERNAL_STORAGE is pointing towards wrong path (i.e. /sdcard). This PR fixes the wrong path.

EXTERNAL_STORAGE is used by other components (like VTS for example)

2024-03-06 15:12 UTC, softing-amr commented
> When an external storage either SSD or SDCard is present; it always mounted at /mnt/softing/softing_ssd_X

I have just double-checked on my Sony image version pdx223-1.3.4 and the mount path is
`/mnt/softing/softing_ssd`
and not
`/mnt/softing/softing_ssd_X`
And `/mnt/softing/softing_ssd` is also what we want to have.

![grafik](https://github.com/SoftingAE-VCPI/VCPI.android.platform.system.core/assets/121190462/fa4f2076-7b93-4de4-b16a-84485a65b06a)


>Currently, the env variable EXTERNAL_STORAGE is pointing towards wrong path (i.e. /sdcard). This PR fixes the wrong path.
If at all, I think it needs to be fixed by setting EXTERNAL_STORAGE to 
`/mnt/softing/softing_ssd`
and not
`/mnt/softing/softing_ssd_0`

However I did not yet fully understand what this path is used for.

> EXTERNAL_STORAGE is used by other components (like VTS for example)

What is VTS (Do you mean [Vendor Test Suite](https://source.android.com/docs/core/tests/vts)?
How it it related to EXTERNAL_STORAGE?

We don't want that Applications other than Softing applications to rely on or install anyting onto the SSD.
So e.g. the Documents/Download folder should not be stored on the SSD, because the ssd will not be powered depending on if the VCPI is externally powered.

I have added @softing-ncr to the discussion, because he has knows how Parameter-Server is handing the SSD.

2024-03-07 08:27 UTC, ahsan-l4b commented
> I have just double-checked on my Sony image version pdx223-1.3.4 and the mount path is `/mnt/softing/softing_ssd` and not `/mnt/softing/softing_ssd_X` And `/mnt/softing/softing_ssd` is what we want to have.
> 

@softing-amr - I have re-checked on my side and the results are now different. Seems some recent development in Parameter-Server has changed it. 

Will adapt to the new changes.
![vcpi-449](https://github.com/SoftingAE-VCPI/VCPI.android.platform.system.core/assets/138857697/37339e05-274f-491f-805f-7eb7f982b8de)

> 
> If at all, I think it needs to be fixed by setting EXTERNAL_STORAGE to `/mnt/softing/softing_ssd` and not `/mnt/softing/softing_ssd_0`
> 

Previously it was different. Now, SDCard mounts at `/mnt/softing/usb_storage_0`. Will change `EXTERNAL_STORAGE` accordingly.



> However I did not yet fully understand what this path is used for.
> What is VTS (Do you mean [Vendor Test Suite](https://source.android.com/docs/core/tests/vts)? How it it related to EXTERNAL_STORAGE?

The EVN variable is used by Android Test Suite (CTS & VTS). The test suite writes test information to the sdcard. Incorrect path to the external storage leads to failure of the test suite.

2025-06-16 09:54 UTC, closed without merging